-- Active: 1683725252949@@127.0.0.1@3306@asqlp

SELECT CURDATE();


SELECT DATE_ADD(CURDATE(), INTERVAL 5 MONTH);


SELECT LAST_DAY(DATE_ADD(CURDATE(), INTERVAL 5 MONTH));


SELECT DATEDIFF(LAST_DAY(DATE_ADD(CURDATE(), INTERVAL 5 MONTH)), CURDATE()) AS 'days';